### ISSUE TITLE
How to use with docker?

### ISSUE THREAD

**Issue by Akruidenberg** [hn/restic2influx#1]
Im currently testing Restic with the [https://github.com/djmaze/resticker](url) container and it would be nice to use this with restic2influx. However, I dont know how to to use this with the `RESTIC_BACKUP_ARGS` envs.

Can you help me with this problem? @hn ?

**Comment by hn** [comment]
`restic2influx` cannot be used directly as an argument of `restic`, but you have to pass the JSON output of `restic` to `restic2influx`. You have to ask the maintainer of `resticker` if he can set up this possibility.
